// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: filament_dryer

#ifndef _FILAMENT_DRYER_UI_H
#define _FILAMENT_DRYER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_controlTemp;
extern lv_obj_t * ui_desiredTemp;
extern lv_obj_t * ui_controlFan;
extern lv_obj_t * ui_desiredFan;
extern lv_obj_t * ui_currentTemp;
extern lv_obj_t * ui_currentHumid;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
