// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: filament_dryer

#ifndef _FILAMENT_DRYER_UI_H
#define _FILAMENT_DRYER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_filament_png);    // assets/filament.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
